// Gemini Multimodal Vision helper for Snack Detective By Devdarsh
const fs = require('fs');
const path = require('path');

const ENV_FILE = path.join(process.cwd(), '.env');

function getServerApiKey() {
  // 1. First check process.env (Vercel environment variables or pre-set)
  if (process.env.GEMINI_API_KEY && process.env.GEMINI_API_KEY.trim().length > 5) {
    return process.env.GEMINI_API_KEY.trim();
  }

  // 2. Fallback to local .env file if it exists
  if (fs.existsSync(ENV_FILE)) {
    try {
      const content = fs.readFileSync(ENV_FILE, 'utf-8');
      const lines = content.split('\n');
      for (const line of lines) {
        const trimmed = line.trim();
        if (trimmed && !trimmed.startsWith('#') && trimmed.includes('=')) {
          const [key, ...vals] = trimmed.split('=');
          if (key.trim() === 'GEMINI_API_KEY') {
            const val = vals.join('=').trim().replace(/^["']|["']$/g, '');
            if (val) return val;
          }
        }
      }
    } catch (e) {
      console.warn('Could not read .env file:', e.message);
    }
  }

  return '';
}

function getEffectiveApiKey(clientKey) {
  if (clientKey && typeof clientKey === 'string' && clientKey.trim().length > 5) {
    return clientKey.trim();
  }
  return getServerApiKey();
}

const VISION_MODELS = ['gemini-flash-latest', 'gemini-3-flash-preview', 'gemini-3.1-flash-lite-preview'];

async function callGeminiVision(base64Image, clientKey = null) {
  const apiKey = getEffectiveApiKey(clientKey);
  if (!apiKey) {
    throw new Error('No Gemini API key found! Please configure GEMINI_API_KEY in Vercel Environment Variables, in local .env, or use BYOK in Settings (⚙️).');
  }

  const cleanBase64 = base64Image.replace(/^data:image\/\w+;base64,/, '');

  const prompt = `
You are Detective Pip, a friendly cartoon fox detective for kids aged 8-11 in a school AI competition.
Look at this image of a snack carefully.
1. Identify EXACTLY what food is shown in this image.
   - If it is an apple, call it an Apple (or specific variety like Crisp Red Apple, Tart Green Apple).
   - If it is a banana, carrot, cookie, chips, donut, sandwich, broccoli, etc., name it accurately.
   - DO NOT confuse apples with bananas or other fruits. Look closely at colors, shapes, and textures.
2. Classify whether this is a "Healthy" snack or a "Treat".
   - Healthy: fruits, vegetables, yogurt, nuts, seeds, whole grains.
   - Treat: cookies, cakes, potato chips, candy, donuts, sodas, sugary processed snacks.
3. Return ONLY valid JSON (no markdown fences, no extra text) with this exact format:
{
  "exactFood": "Name of the exact food identified (e.g. Crisp Red Apple)",
  "verdict": "Healthy" or "Treat",
  "confidence": 0.98,
  "superpower": "Short 3-5 word nutrient superpower (e.g. Vitamin C & Pectin Fiber Shield 🍎)",
  "pipSpeech": "1-2 friendly, enthusiastic sentences spoken by Detective Pip describing what he sees and why it fuels the body. Always encouraging, never shaming treats.",
  "balanceTip": "A fun detective tip on how this food helps the body or how to enjoy it in healthy balance."
}
`.trim();

  const payload = {
    contents: [
      {
        parts: [
          { text: prompt },
          {
            inline_data: {
              mime_type: 'image/jpeg',
              data: cleanBase64
            }
          }
        ]
      }
    ],
    generationConfig: {
      temperature: 0.1,
      maxOutputTokens: 600
    }
  };

  let lastError = null;

  for (const modelName of VISION_MODELS) {
    try {
      const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload)
      });

      if (!response.ok) {
        const errText = await response.text();
        console.warn(`Model ${modelName} returned status ${response.status}: ${errText.substring(0, 150)}`);
        lastError = new Error(`Gemini API Error (${response.status}): ${errText}`);
        if (response.status === 503 || response.status === 404 || response.status === 429) {
          continue;
        } else {
          throw lastError;
        }
      }

      const json = await response.json();
      const text = json.candidates?.[0]?.content?.parts?.[0]?.text;
      if (!text) throw new Error('No response text generated by Gemini model.');

      const cleanedText = text.replace(/```json/g, '').replace(/```/g, '').trim();
      return JSON.parse(cleanedText);
    } catch (err) {
      lastError = err;
      console.warn(`Attempt with ${modelName} failed: ${err.message}`);
    }
  }

  throw lastError || new Error('All vision models failed to respond.');
}

async function callGeminiPipChat(question, snackName, verdict, clientKey = null) {
  const apiKey = getEffectiveApiKey(clientKey);
  if (!apiKey) {
    return `Aha! Detective Pip says: enjoying ${snackName} with plenty of fresh water and balance is your true detective superpower!`;
  }

  const prompt = `
You are Detective Pip, a cheerful cartoon fox detective helping kids aged 8-11 learn about food and healthy choices.
A child scanned their ${snackName} (which was classified as a ${verdict}) and asks you:
"${question}"
Answer in 1-2 friendly, energetic, kid-friendly sentences in character.
Be scientifically helpful, encouraging, and never make them feel bad about eating treats.
`.trim();

  for (const modelName of VISION_MODELS) {
    try {
      const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${modelName}:generateContent?key=${apiKey}`;
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: { temperature: 0.6, maxOutputTokens: 250 }
        })
      });

      if (response.ok) {
        const json = await response.json();
        const reply = json.candidates?.[0]?.content?.parts?.[0]?.text;
        if (reply) return reply.trim();
      }
    } catch (e) {
      console.warn(`PipChat with ${modelName} failed:`, e.message);
    }
  }

  return `Aha! Detective Pip says: enjoying your ${snackName} with good balance and plenty of water is pure detective brilliance! 🌟`;
}

module.exports = {
  getServerApiKey,
  getEffectiveApiKey,
  callGeminiVision,
  callGeminiPipChat
};
